
export const buttonSaveUserText = "Kaydet"
export const buttonListUsersText = "Listele"
export const buttonDeleteAllUsersText = "Tümünü Sil"
export const alertInvalidOperationText = "Geçersiz işlem"
export const alertSaveSuccessText = "Kayıt başarıyla eklendi"
export const alertSaveFailText = "Eklenemedi"
export const alertUnexpectedStateText = "Beklenmedik bir durum oluştu"
export const alertEmptyFieldsText = "Alanlar boş geçilemez"
export const alertNoSuchUserText = "Henüz hiç bir kullanıcı eklenmemiş"
export const placeholderUsernameText = "Kullanıcı adı"
export const placeholderNameText = "Ad"
export const placeholderSurnameText = "Soyad"
export const placeholderEmailText = "Email"
